# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rohan
tagline:          'Personal Web Page'
description:      'Technology Enthusiast'
url:              
baseurl:          /

author:
  name:           'Rohan Bharadwaj'
  url:            https://github.com/rohanbharadwaj

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/rohanbharadwaj
