# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rohan
tagline:          'Personal Web Page'
description:      'Technology Enthusiast'
avatar:https://avatars1.githubusercontent.com/u/4630253?v=3&u=d62326a98714440e1ba22e647686783a283b65c0&s=140
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rohanbharadwaj
